### ISSUE TITLE
docs: Use a complementary color

### ISSUE THREAD

**Issue by Kikobeats** [Kikobeats/tom-microservice#4]
![dfikygiu](https://user-images.githubusercontent.com/2096101/42399466-3103f128-816e-11e8-9e6b-8aeb98524f29.jpg)

Feedback from @aarongarciah

> Veo demasiado naranja “principal”: enlaces, textos, bloques de código, títulos, menú, etc. Quizás estaría bien encontrar un color complementario al --secondary-color (#ff5f4a) y aplicarlos a los bloques de código . Con esta herramienta he encontrado este verde complementario (#10B263) y y otro tono de verde (#8dc891) para los bordes de las cajas de código y no queda mal, por si le quieres dar una vuelta. Un azul tampoco estaría mal.

https://color.adobe.com/create/color-wheel/?base=0&rule=Complementary&selected=3&name=My%20Color%20Theme&mode=rgb&rgbvalues=1,0.37254901960782716,0.29019607843137263,0.7,0.1989058606868034,0.13313725490196085,1,0.460946809663078,0.3901960784313726,0.06313725490196087,0.7,0.38678010722678985,0.29019607843137263,1,0.650906400295868&swatchOrder=0,1,2,3,4

**Comment by aarongarciah** [comment]
Nice color that cyan
