### ISSUE TITLE
docs: Adjust responsive

### ISSUE THREAD

**Issue by Kikobeats** [Kikobeats/tom-microservice#5]
Feedback from @aarongarciah

> Quítale el `width: 100vw` al \<main\> ya que hace que desaparezca el padding del \<article\> cuando el viewport es menor que el contenido. Los elementos de bloque por defecto toman el 100% del ancho de su contenedor, salvo que estén fletados, sean un flex-item o tengan otra regla que modifique su flujo natural en el documento. Esto es debido a que la unidad vw toma en cuenta las barras de scroll para hacer sus cálculos. Adjunto captura:

![mx6e8tlb](https://user-images.githubusercontent.com/2096101/42399578-a71f6ff4-816e-11e8-8e2f-dc63f761fabd.png)

> Si le quitas el `width: 100vw` se ve bien y podrás quitar el `overflow-x: hidden` del body. Se verá bien. Adjunto captura:

![ij53whgt](https://user-images.githubusercontent.com/2096101/42399585-aacd2114-816e-11e8-8b28-c4e052a68e41.png)

> - El menú lateral en viewports de tamaño “tablet” podría reducir su ancho para dar más espacio al contenido. Adjunto captura.

![4un11fht](https://user-images.githubusercontent.com/2096101/42399603-c46673be-816e-11e8-8062-7dc3eb7f205b.png)

> En tamaños de viewport “mobile”, el hamburger prácticamente no se ve. Lo movería arriba a la izquierda, aumentaría su tamaño y lo enmarcaría en un círculo con fondo blanco o similar para mejorar su visibilidad cuando esté encima de algún texto. Con lo de círculo blanco me refiero a esto

https://codepen.io/andyNroses/pen/AXwPkb

**Comment by aarongarciah** [comment]
Looks pretty good 😄
